const POWER={Constructor:4,Smelter:4,Assembler:15,Manufacturer:55,Refinery:30,Foundry:16,Packager:10,Blender:75,Converter:250,QuantumEncoder:2000};
export const BELTS={1:60,2:120,3:270,4:480,5:780,6:1200};
export function clean(x=''){return x.replace(/^Desc_/,'').replace(/^Build_/,'').replace(/^BP_EquipmentDescriptor/,'').replace(/Mk([1-9])/g,' Mk.$1').replace(/_C$/,'').replace(/_/g,' ').replace(/([a-z])([A-Z])/g,'$1 $2').trim()}
export function normalize(raw){return Object.values(raw).flatMap(v=>Array.isArray(v)?v:[v]).filter(r=>r?.products?.length&&r.duration>0&&!r.inBuildGun&&!r.inCustomizer&&!r.inWorkshop&&r.producedIn?.length).map((r,i)=>({...r,id:r.className||`recipe_${i}`}))}
export function catalog(rs){const m=new Map();for(const r of rs)for(const p of r.products){m.has(p.item)||m.set(p.item,{id:p.item,name:clean(p.item),recipes:[]});m.get(p.item).recipes.push(r)}return[...m.values()].sort((a,b)=>a.name.localeCompare(b.name))}
export function category(n){if(/ore|coal|bauxite|sulfur|quartz|limestone|sam/i.test(n))return'Rohstoffe';if(/ingot/i.test(n))return'Barren';if(/water|oil|fuel|acid|solution|residue|nitrogen/i.test(n))return'Fluids';if(/wire|cable|circuit|computer|quickwire|limiter/i.test(n))return'Elektronik';return'Bauteile'}
const baseMachine=id=>{const name=clean(id),family=Object.keys(POWER).find(x=>name.includes(x))||name;return{id,name,family,power:POWER[family]||0}}
function configuredMachine(id,opt,itemId){const b=baseMachine(id),cfg=opt.machineConfig?.[itemId]||{},tier=Math.max(1,+cfg.tier||1),clock=Math.min(250,Math.max(1,+cfg.clock||100)),name=b.name.replace(/ Mk\.\d+/,'')+(tier>1?` Mk.${tier}`:b.name.match(/Mk\.\d+/)?' Mk.1':'');return{...b,name,tier,clock,speed:tier*(clock/100),power:b.power*Math.pow(tier,0.7)*Math.pow(clock/100,1.321929)}}
export function solve(itemId,rate,recipes,opt={}){const by=new Map;for(const r of recipes)for(const p of r.products){by.has(p.item)||by.set(p.item,[]);by.get(p.item).push(r)}const nodes=[],edges=[],warnings=[],path=new Set;let seq=0;
function edge(from,to,id,flow){const max=opt.maxBelt==='auto'?6:+opt.maxBelt||6,allowed=Object.keys(BELTS).map(Number).filter(x=>x<=max),mk=allowed.find(x=>BELTS[x]>=flow)||max,cap=BELTS[mk],lines=Math.max(1,Math.ceil(flow/cap)),bottleneck=flow>cap;edges.push({from,to,itemId:id,flow,mk,cap,lines,bottleneck});if(bottleneck)warnings.push(`${clean(id)}: ${flow.toFixed(1)}/min benötigt ${lines}× Belt Mk.${mk}`)}
function walk(id,need,parent=null,depth=0){const nid=`n${seq++}`,choices=by.get(id)||[];if(!choices.length||path.has(id)){const n={id:nid,type:'raw',itemId:id,name:clean(id),rate:need,depth,children:[]};nodes.push(n);if(parent)edge(nid,parent,id,need);return n}const chosen=opt.recipeSelections?.[id],r=(chosen?choices.find(x=>x.id===chosen):null)||choices.find(x=>x.alternate===false)||choices.find(x=>!x.alternate)||choices[0],prod=r.products.find(p=>p.item===id),base=(prod.amount*60/r.duration),m=configuredMachine(r.producedIn[0],opt,id),count=need/(base*m.speed),n={id:nid,type:'prod',itemId:id,name:clean(id),rate:need,count,machine:m,recipe:r,depth,children:[]};nodes.push(n);if(parent)edge(nid,parent,id,need);path.add(id);for(const ing of r.ingredients){const f=count*m.speed*ing.amount*60/r.duration;n.children.push(walk(ing.item,f,nid,depth+1))}path.delete(id);return n}
const root=walk(itemId,rate);const items={},raw={},machines={};for(const n of nodes){items[n.itemId]=(items[n.itemId]||0)+n.rate;if(n.type==='raw')raw[n.itemId]=(raw[n.itemId]||0)+n.rate;else{const k=n.machine.name;machines[k]||={name:k,count:0,power:n.machine.power,powerTotal:0};machines[k].count+=n.count;machines[k].powerTotal+=n.count*n.machine.power}}return{root,nodes,edges,warnings,totals:{items,raw,machines,machineCount:Object.values(machines).reduce((s,m)=>s+m.count,0),power:Object.values(machines).reduce((s,m)=>s+m.powerTotal,0),rawRate:Object.values(raw).reduce((a,b)=>a+b,0)}}}
